services:
  pgadmin4:
    image: dpage/pgadmin4:9.10
    container_name: pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com # 邮箱
      - PGADMIN_DEFAULT_PASSWORD=password # 密码
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
    ports:
      - 5050:80
    volumes:
      - ./data:/var/lib/pgadmin
